{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fclipboard-backend.fullname" . }}-postgres
  labels:
    {{- include "fclipboard-backend.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fclipboard-backend.fullname" . }}-postgres
  labels:
    {{- include "fclipboard-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "fclipboard-backend.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fclipboard-backend.fullname" . }}-postgres
  labels:
    {{- include "fclipboard-backend.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "fclipboard-backend.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fclipboard-backend.name" . }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fclipboard-backend.name" . }}-postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fclipboard-backend.fullname" . }}-postgres
                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage | default "5Gi" }}
        {{- if .Values.postgres.storageClass }}
        storageClassName: "{{ .Values.postgres.storageClass }}"
        {{- end }}
{{- end }}
