apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: fclipboard
spec:
  selector:
    matchLabels:
      application: fclipboard
      component: web
  template:
    metadata:
      labels:
        application: fclipboard
        component: web
    spec:
      containers:
        - image: harbor.lingmind.cn/teabrew/fclipboard-web:20251129112655
          name: web
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
